[package]
name = "sei-discord"
version = "0.1.0"
authors = ["jtexeira <a85504@alunos.uminho.pt>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.9"
